# This file was generated by GoReleaser. DO NOT EDIT.
cask "arca" do
  version "0.6.5"

  on_macos do
    on_intel do
      sha256 "b28202334d4b4958d7868b5f3ed52d545221c7003e08e041dbd2e3ed27c5dc51"
      url "https://github.com/arenzana/arca/releases/download/v#{version}/arca_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "0d449b9318785826dbce2108134f299ccd49b35a6713be03a715c78bc75a7148"
      url "https://github.com/arenzana/arca/releases/download/v#{version}/arca_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "21e9f59e786b766afbc7303da1dba3c4f171efdf53ba20d586e4ee4dd9e4a351"
      url "https://github.com/arenzana/arca/releases/download/v#{version}/arca_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "48f2b48cbe66e176276199a500827311f50189723410125e9cb07f79518d0260"
      url "https://github.com/arenzana/arca/releases/download/v#{version}/arca_#{version}_linux_arm64.tar.gz"
    end
  end

  name "arca"
  desc "age-encrypted, file-based secrets manager built to sit safely in front of AI agents"
  homepage "https://github.com/arenzana/arca"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "arca"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/arca"]
    end
  end

  # No zap stanza required

end
