# This file was generated by GoReleaser. DO NOT EDIT.
cask "arca" do
  version "0.10.2"

  on_macos do
    on_intel do
      sha256 "7343b59aaac7980db08fdfe1eb3ce5c596c5560dc0271e825395551e9ccf0c1e"
      url "https://github.com/arenzana/arca/releases/download/v#{version}/arca_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "83acb71493ea2d07e0d5b4145a708b063129daad507084d6ba75959b3c6dd3b9"
      url "https://github.com/arenzana/arca/releases/download/v#{version}/arca_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "6ffa6be3a717c7ffecda4794f0fb2327e915f35ce4265b198ea1d4ba6795ac2e"
      url "https://github.com/arenzana/arca/releases/download/v#{version}/arca_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "f4d49e423e018399c960e0f2e756c48fa12f7c8cf161cde8a92a11e3b817101e"
      url "https://github.com/arenzana/arca/releases/download/v#{version}/arca_#{version}_linux_arm64.tar.gz"
    end
  end

  name "arca"
  desc "age-encrypted, file-based secrets manager built to sit safely in front of AI agents"
  homepage "https://github.com/arenzana/arca"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "arca"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/arca"]
    end
  end

  # No zap stanza required

end
