# This file was generated by GoReleaser. DO NOT EDIT.
cask "arca" do
  version "0.10.3"

  on_macos do
    on_intel do
      sha256 "e7dc93383520c1918146cc7d17284dea0c822f3502efb7e5226abb1f1ef45fae"
      url "https://github.com/arenzana/arca/releases/download/v#{version}/arca_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "c423130d235790502d2637a946e52135b94e5cb83d1c078a732f6161047570b6"
      url "https://github.com/arenzana/arca/releases/download/v#{version}/arca_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "fa1bbd033ab6394af24bc38213f27d35576ddefce528b355bd6444dcdc2acaa8"
      url "https://github.com/arenzana/arca/releases/download/v#{version}/arca_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "39036c8bc4d5ab9b48832a1bf5fad2302f43382a05b2cc494d10569bc98d6c5a"
      url "https://github.com/arenzana/arca/releases/download/v#{version}/arca_#{version}_linux_arm64.tar.gz"
    end
  end

  name "arca"
  desc "age-encrypted, file-based secrets manager built to sit safely in front of AI agents"
  homepage "https://github.com/arenzana/arca"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "arca"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/arca"]
    end
  end

  # No zap stanza required

end
